<?php

namespace Miky\Bundle\InstallerBundle\Repository;

/**
 * InstallationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstallationRepository extends \Doctrine\ORM\EntityRepository
{
}
